###  http://localhost:8083/ddd/api-ui
##### Show Cart #################################
POST http://localhost:8083/ddd/shopping/showcart
Accept: application/json
Content-Type: application/json

{
  "code":1
}
##### Delete From Cart #################################
DELETE http://localhost:8083/ddd/shopping/deletefromcart
Accept: application/json
Content-Type: application/json

{
    "code":1
}
##### cancel  Cart #################################
DELETE http://localhost:8083/ddd/shopping/cancelcart
Accept: application/json
Content-Type: application/json

{
  "code":2
}
##### Add To Cart #################################
PUT http://localhost:8083/ddd/shopping/addtocart
Accept: application/json
Content-Type: application/json

{
  "cartpk": null,
  "customerfk": 3,
  "productfk": 1,
  "quantity": 10,
  "price": 20.20
}
##### Close Cart #################################
POST http://localhost:8083/ddd/shopping/closecart
Accept: application/json
Content-Type: application/json

{
  "code":2
}